<a href="https://colab.research.google.com/github/FlashChoi5657/iTshirt/blob/main/Class_prep_01_python_basic_print%2C_docstring%2C_auto_intent_etc_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 환경구성
    Anaconda 환경
    jupyter notebook

### Jupyter notebook 
    mode
        - 명령모드(esc)
        - 편집모드(셀 선택 후 enter)

        - 셀이 편집 가능합니다.

    Style
        - markdown
        - code

    
    단축키
        - shift+enter : 아래 셀로 내려가면서 실행
        - ctrl+enter : 현재 셀에 머무르면서 실행      
        - Ctrl + M D : 셀 삭제
        - a : 현재 선택된 셀 위에 새로운 셀 생성
        - b : 현재 선택된 셀 아래에 새로운 셀 생성
        - z : Undo
        - spacebar : 현재 화면을 위로 올림

#### magic command
    - % : 한 줄의 magic command를 동작
    - %% : 셀 단위의 magic command를 동작
    - 주요 magic command
        %pwd : 현재 jupyter notebook 파일의 경로
        %ls : 현재 디렉토리의 파일 리스트 출력
        %whos : 현재 선언된 변수들을 출력
        %reset : 현재 선언된 변수들을 전부 삭제

In [1]:
%pwd
%ls
%whos

sample_data/
Interactive namespace is empty.


#### shell command
    - jupyter notebook을 실행한 shell 환경의 명령을 사용
    - 명령어 앞에 !를 붙여서 실행    

In [2]:
!pip install SimpleITK

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 48.4 MB 2.2 MB/s 


### 기본 문법
    - 변수 선언, 식별자, 자료형, 형변환, 연산자

#### 주석과 출력
    - 주석 : 작성한 문장 맨 앞에 #을 붙이면 주석처리
    - 출력 : 셀의 마지막 문장 하나만 결과로 출력
            여러 결과나 코드 중간 변수 값을 출력하고 싶을때 print(출력물)로 작성

In [3]:
print('Hello Python')
# print('안녕 파이썬')
print('안녕하세요')

"""
여러줄의 주석은 세번쓰기
코드에 전혀 영향을 주지 않는다
"""

Hello Python
안녕하세요


'\n여러줄의 주석은 세번쓰기\n코드에 전혀 영향을 주지 않는다\n'

In [ ]:
"""이 안에 설명을 쓰시면 됩니다."""

In [6]:
for i in range(1,11):
    print('안녕하세요')

안녕하세요
안녕하세요
안녕하세요
안녕하세요
안녕하세요
안녕하세요
안녕하세요
안녕하세요
안녕하세요
안녕하세요


 - 파이썬 수는 0 부터 시작합니다.

    - docstring : 함수의 사용법을 설명 (단축키: shift+tab)
    - 자동완성 : 코드의 일부분만 작성하고 뒷부분을 자동으로 채워주는 기능 (단축키: tab)

In [7]:
import random # random 라이브러리를 불러오는 것
random.randint
random.random

<function Random.random>

#### 변수 선언
    RAM 저장 공간에 값을 할당하는 행위

In [8]:
a = 1
b = 2
c = a + b
print(c)

3


In [10]:
d, e = 3, 4
f = g = 5
print(d, e, f, g)

3 4 5 5


In [ ]:
g = h = 70
g, h

In [13]:
import numpy as np # numpy 라이브러리를 불러옴
a = np.random.randint(0,10,(10,10)) # 행렬의 크기가 10x10이고 값들은 0부터 9까지

b = np.random.randint(11,20,(10,10)) 
print(a, "\n",b,"\n", a+b)

[[4 2 8 7 6 6 5 6 5 6]
 [1 6 4 5 7 6 0 8 5 1]
 [2 1 8 5 4 1 5 9 3 7]
 [7 4 0 3 6 7 3 9 9 6]
 [2 0 7 6 3 8 9 8 0 4]
 [6 3 5 4 5 7 6 6 3 7]
 [7 5 6 5 5 9 1 6 3 4]
 [0 0 8 0 8 1 7 1 8 5]
 [6 4 2 1 9 7 6 6 5 3]
 [0 3 8 8 9 6 0 4 2 2]] 
 [[11 18 11 17 15 12 19 19 13 17]
 [15 15 13 19 18 19 15 14 15 12]
 [15 19 17 11 16 12 17 11 17 13]
 [12 18 13 12 15 16 11 16 11 19]
 [13 16 19 12 15 18 17 16 19 18]
 [19 19 17 19 13 18 15 15 12 13]
 [16 11 12 18 15 19 13 14 11 18]
 [19 15 18 17 13 15 17 12 14 19]
 [13 16 14 15 16 16 17 15 12 18]
 [14 19 15 12 16 11 13 11 18 17]] 
 [[15 20 19 24 21 18 24 25 18 23]
 [16 21 17 24 25 25 15 22 20 13]
 [17 20 25 16 20 13 22 20 20 20]
 [19 22 13 15 21 23 14 25 20 25]
 [15 16 26 18 18 26 26 24 19 22]
 [25 22 22 23 18 25 21 21 15 20]
 [23 16 18 23 20 28 14 20 14 22]
 [19 15 26 17 21 16 24 13 22 24]
 [19 20 16 16 25 23 23 21 17 21]
 [14 22 23 20 25 17 13 15 20 19]]


#### 식별자
    - 변수, 함수, 클래스, 모듈 등의 이름
    - 규칙
        - 소문자, 대문자, 숫자, _ (low dash / under_score)
        - 가장 앞에 숫자 사용 불가
        - 예약어 사용 불가 (def, class, int, ...) : 이미 python에서 문법적으로 정의되어 있는 식별자
        - Convention
            - snake_case : 변수, 함수
            - CamelCase : class

In [14]:
import keyword
print(keyword.kwlist) 

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


#### 데이터 타입
    - RAM 저장 공간을 효율적으로 사용하기 위해서 저장 공간의 타입 설정
    - 동적 타이핑
        - 변수 선언 시 저장되는 값에 따라서 자동으로 타입이 설정

In [17]:
%whos

Interactive namespace is empty.


In [16]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [ ]:
%whos

Interactive namespace is empty.


In [19]:
a = 1
b = 'python'
c = 1.0
type(a), type(b), type(c)

(int, str, float)

In [ ]:
# 심플한 파이선의 철학
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
